// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3J2F_XSdUUMFTfUW_bJpGkQoJvtWUN9A',
    appId: '1:319877239326:web:b3f0b914fe4f64f18e940f',
    messagingSenderId: '319877239326',
    projectId: 'spr01-5bee0',
    authDomain: 'spr01-5bee0.firebaseapp.com',
    storageBucket: 'spr01-5bee0.appspot.com',
    measurementId: 'G-HPNPRMGZZQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC75nH-REdkONYXjoyzSfgltN3Ci4lvtYk',
    appId: '1:319877239326:android:6bc7e4bc0e9409e28e940f',
    messagingSenderId: '319877239326',
    projectId: 'spr01-5bee0',
    storageBucket: 'spr01-5bee0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3Yc0-lWsmdXGu5V917ovQhUNpR282HXg',
    appId: '1:319877239326:ios:e139702feb5737018e940f',
    messagingSenderId: '319877239326',
    projectId: 'spr01-5bee0',
    storageBucket: 'spr01-5bee0.appspot.com',
    iosBundleId: 'com.example.garkAcademy',
  );

}