// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRxZix-M8OcQ2g2hppY6AERS-j9If2boU',
    appId: '1:864604067490:web:533c3c9d13ee3985ea69fb',
    messagingSenderId: '864604067490',
    projectId: 'lifriqi-7a5dc',
    authDomain: 'lifriqi-7a5dc.firebaseapp.com',
    storageBucket: 'lifriqi-7a5dc.appspot.com',
    measurementId: 'G-CZ22GBZCGX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCja3dk97NMSFCt5dD7joD8kcnBR5JiOzw',
    appId: '1:864604067490:android:5be990a8888370a2ea69fb',
    messagingSenderId: '864604067490',
    projectId: 'lifriqi-7a5dc',
    storageBucket: 'lifriqi-7a5dc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtNQ-Ax9K7WIE6iZF0EzgJKIEmoV3RIog',
    appId: '1:864604067490:ios:d736382eb6d366b1ea69fb',
    messagingSenderId: '864604067490',
    projectId: 'lifriqi-7a5dc',
    storageBucket: 'lifriqi-7a5dc.appspot.com',
    iosBundleId: 'com.spr01.clubafricain',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtNQ-Ax9K7WIE6iZF0EzgJKIEmoV3RIog',
    appId: '1:864604067490:ios:82c71186be1531e0ea69fb',
    messagingSenderId: '864604067490',
    projectId: 'lifriqi-7a5dc',
    storageBucket: 'lifriqi-7a5dc.appspot.com',
    iosBundleId: 'com.example.garkAcademy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCRxZix-M8OcQ2g2hppY6AERS-j9If2boU',
    appId: '1:864604067490:web:5d1197cf52bc2d00ea69fb',
    messagingSenderId: '864604067490',
    projectId: 'lifriqi-7a5dc',
    authDomain: 'lifriqi-7a5dc.firebaseapp.com',
    storageBucket: 'lifriqi-7a5dc.appspot.com',
    measurementId: 'G-BXJ11423H4',
  );
}
